### PR TITLE
feat!: upgrade to cdk v2

### LINKED ISSUE #98: Support for CDK v2 would be nice :-)
Hello!

Support for CDK v2 would be nice! I might try and see if I can get this working in a fork, but it's unclear how I will actually be able to publish/consume the npm package from a forked repository.

### PR DESCRIPTION
**Pull request by jabalsad**
This change removes support for cdk v1 since it is deprecated.

Fixes #98

### CODE REVIEW

**Comment by jabalsad** [comment]
A few open items:

1. I'm not entirely sure what testing I can perform besides `npx projen test`. It's difficult for me to add this project as a dependency until it is published.
2. The snapshots directory has a bunch of changes, presumably from running `npx projen test`. Is it okay to commit these?
3. How does the versioning strategy work? Will it automatically get a version bump to 0.2.x ?

**Comment by jabalsad** [comment]
Hmm, okay I see now. My changes don't play nicely with projen. Let me try and fix that.

**Comment by jabalsad** [comment]
It appears that this projen module also uses cdk v1 🤦 :
https://github.com/projen/projen/blob/main/docs/awscdk-construct.md

**Comment by misterjoshua** [comment]
Your changes look good at first review, but it looks like I'll need to upgrade projen so the build can succeed. I'll fix this aspect of the project tonight and let you know.

**Comment by misterjoshua** [comment]
>     1. I'm not entirely sure what testing I can perform besides `npx projen test`. It's difficult for me to add this project as a dependency until it is published.

I have a variety of integration test apps that one can run. i.e., `yarn integ:cloudwatch-alarm deploy`. They're all the ones starting with `integ:`. But for testing in your project, another thing you can do is type `yarn link` in this project's repository and type `yarn link @wheatstalk/cdk-intrinsic-validator` in your project. This way you can use your local linked copy of this project directly.

>     2. The snapshots directory has a bunch of changes, presumably from running `npx projen test`. Is it okay to commit these?

Yes. The CI will fail if a change reflected in those snapshots is not committed.

>     3. How does the versioning strategy work? Will it automatically get a version bump to 0.2.x ?

I've added an exclamation point to this PR `feat!: ...` so projen can detect the breaking change and bump to 0.2.x.

>     4. Mergify summary workflow is failing but it's not clear to me what it means.

I've updated projen so that it generates an up-to-date mergify configuration. It's no longer a problem. :)


Once we've resolved the issue you spotted in #102, I'll circle around to this PR and do some more testing. I expect we should be able to get this PR merged this week without any major issues.

**Pull request merged**
