### PR TITLE
feat: support cloudwatch composite alarm monitoring

### PR DESCRIPTION
**Pull request by jabalsad**
this change describes both composite and metric alarms when finding alarms in alarming state.

The default behaviour on the `DescribeAlarms` API call is to only include metric alarms in the response.

ref; https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatch.html#describeAlarms-property

### CODE REVIEW

**Comment by misterjoshua** [comment]
You'll probably need to do a full `git clean -fdx`, `yarn install`, and `yarn build` to update the assets hashes. I'm noticing that the project's build is a little out of sorts at the moment due to the projen update. 😅

Am I correct in assuming that lacking support for composite alarms is the cause behind #102?

**Comment by jabalsad** [comment]
It's not clear to me that the two are related yet. I'll run the commands suggested.

**Comment by jabalsad** [comment]
Actually I'm pretty sure the two are unrelated. The alarm-status-checker.ts runs successfully.

**Comment by misterjoshua** [comment]
The alarm status checker appears not to be detecting alarming composite alarms. I'm going to make an adjustment to fix the issue.

**Review by misterjoshua — APPROVED** [review]
Looks good to me. Thanks for contributing!

**Pull request merged**
