### PR TITLE
fix: use the correct nodejs lambda handler function for cw alarm validator

### PR DESCRIPTION
**Pull request by jabalsad**
It appears the current configuration is trying to invoke an incorrect lambda function handler:

```
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "check-alarm-status.checkAlarmStatus is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: check-alarm-status.checkAlarmStatus is undefined or not exported",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:283:11)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:34)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

Am I missing something obvious? I think the PR fixes the issue.

### CODE REVIEW

**Comment by misterjoshua** [comment]
Sounds like a bundling error in the latest release - The entrypoint for the lambdas should be exporting `handler`. I'll see if I can reproduce this by running the integration tests.

**Comment by jabalsad** [comment]
This was from the main (1.x) branch. Not sure why the snapshot files are included - could be from running `npx projen build`?

**Comment by misterjoshua** [comment]
> This was from the main (1.x) branch. Not sure why the snapshot files are included - could be from running `npx projen build`?

The snapshots are updated every time `yarn test` runs - it helps to keep track of the runtime file changes. When I updated projen in #100, many of the bundled deps updated, and so the asset hashes changed, resulting in these conflicts. I'll rerun the snapshots for this branch so I can see how CI likes it and so I can run the unit tests.

**Comment by jabalsad** [comment]
Seems like maybe this branch needs to be rebased from main.

**Comment by misterjoshua** [comment]
> Seems like maybe this branch needs to be rebased from main.

I've merged main to this branch. It looks like this fixed the CI problem. When Mergify finishes up this PR, it'll do the rebasing for us.

I'm just waiting for the integration tests to finish at the moment.

**Review by misterjoshua — APPROVED** [review]
LGTM! Thanks for fixing this problem!

**Pull request merged**
